### ISSUE TITLE
LightLine用グリフで左右セパレータの幅が異なる

### ISSUE THREAD

**Issue by azarashichop** [miiton/Cica#10]
メモ帳で表示確認してみたところ、以下のような状態でした。
* 左側セパレータ・・・全角扱い
* 右側セパレータ・・・半角扱い

ambiwidth、スペースなどを入れて何とか調整を
試みましたがうまくいきません・・・
回避方法あれば、ご教示ください。

![image](https://cloud.githubusercontent.com/assets/8552118/19728865/fd206e02-9bcf-11e6-8b01-fef636d8db33.png)

**Comment by azarashichop** [comment]
他のエディタ（NoEditor）だときれいに表示されました。
![image](https://cloud.githubusercontent.com/assets/8552118/19799890/019313b2-9d34-11e6-8a03-ce47e826d07f.png)

また、Vimで開いた場合もきれいに表示されました・・・。（下はずれているのが確認できます）
![image](https://cloud.githubusercontent.com/assets/8552118/19799920/2ecbf39e-9d34-11e6-99ab-5607e2495e48.png)


LightLine側の文字処理に起因するものかもしれません・・・。

**Comment by miiton** [comment]
[Cica-Regular.ttf.zip](https://github.com/miiton/Cica/files/560177/Cica-Regular.ttf.zip)

左向きのグリフの幅がおかしかったので修正してみました。
これだとどうでしょうか？

- Mac : iTerm2、MacVim
- Windows 10 : メモ帳、gVim

では大丈夫そうでした

**Comment by azarashichop** [comment]
ご対応ありがとうございます。ZIP版および、repoをプルしての再生成、両方試しました。
おかげさまで、グリフの幅に関してはすべて同じになりました。

LightLineに表示させるとずれてしまうのは、変わらずですが・・・

環境の要因が大きそうなので、少しこちらで調査します。

というわけで、本issueはクローズでOKです。

ありがとうございました。

**Comment by miiton** [comment]
@azarashichop 

はい、ではリリースしてからクローズします。

ちなみに lightlineでずれる件に関してはlightlineのREADMEに記載がありますのでご確認ください。

https://github.com/itchyny/lightline.vim
![itchyny_lightline_vim__a_light_and_configurable_statusline_tabline_for_vim](https://cloud.githubusercontent.com/assets/468745/19841272/621f3b9c-9f4c-11e6-87c3-6e7ff20f13cb.png)
