### ISSUE TITLE
gjyの下端が切れる

### ISSUE THREAD

**Issue by miiton** [miiton/Cica#16]
WindowsのcmderとMacのターミナル( thx! @hnakamur )で確認

**Comment by hnakamur** [comment]
イシュー作成していただいてありがとうございます！

ツイートした内容＋αをこちらにも転機します。

OSのバージョンはOS X Yosemite 10.10.5です。

Cicaフォント2.0.2をmacOSのターミナル.appで使うと18ptだと問題ないのですが15ptとか16ptとかにすると場所によってgjyの下が少しだけ切れてしまいます。添付のスクショの最後の2行です。ウィンドウを切り替えて表示が更新されると治る時もあります。

![cica-2 0 2-on-terminal app](https://user-images.githubusercontent.com/19299/31477941-4fb066ae-af48-11e7-8619-384181dd2311.png)

iTerm2だとCica 2.0.2の15ptでも切れる問題は起きないです。http://Terminal.app で「ボールドフォントを使用」をオフにしていてもiTerm2に比べると太く見えるのも謎です。

![cica-2 0 2-on-iterm2](https://user-images.githubusercontent.com/19299/31478006-5d125c62-af48-11e7-86bb-7a1cafdead60.png)

**Comment by miiton** [comment]
直りそうな気配はしていますがちょっと時間がかかりそうです

## 参考情報

- FontForgeドキュメント - フォント情報
    - https://fontforge.github.io/ja/fontinfo.html#TTF-Metrics
- メッセージ M+ OUTLINE FONTS:行間について #52044 - M+ FONTS - OSDN 
    - https://ja.osdn.net/projects/mplus-fonts/forums/3403/26784/52044/

**Comment by miiton** [comment]
ちなみに太く見えるのはアプリケーションのフォントレンダリングの方法の違いだと思いますので、フォント側で出来るのは太さの違うウェイトを用意するとかかなと思われます。

**Comment by miiton** [comment]
いけてる気がする...!

```py
    _font.os2_winascent = 0
    _font.os2_winascent_add = True
    _font.os2_windescent = 0
    _font.os2_windescent_add = True

    _font.os2_typoascent = -150
    _font.os2_typoascent_add = True
    _font.os2_typodescent = 100
    _font.os2_typodescent_add = True
    _font.os2_typolinegap = 0

    _font.hhea_ascent = -150
    _font.hhea_ascent_add = True
    _font.hhea_descent = 100
    _font.hhea_descent_add = True
    _font.hhea_linegap = 0
```

[CicaTest-iss16-01.zip](https://github.com/miiton/Cica/files/1380685/CicaTest-iss16-01.zip)

**Comment by miiton** [comment]
Windowsで残念なことになっていました

![win10 before-intellij running 2017-10-13 08-16-43](https://user-images.githubusercontent.com/468745/31523497-dcb38c1a-afee-11e7-98f3-260fdfe822d1.png)

**Comment by hnakamur** [comment]
参考情報と調整ありがとうございます。
OSX Yosemite 10.10.5, Terminal.app, CicaTest 15ptでgjyの下が切れないのを私も確認しました。
今晩自宅のWindowsのminttyでも確認してみます（minttyでもgjyの下が切れる現象が出ていました）。

**Comment by miiton** [comment]
ありがとうございます！

Windows解消しました

![win10 before-intellij running 2017-10-13 09-31-16](https://user-images.githubusercontent.com/468745/31525173-4af55eba-aff9-11e7-8917-213e1c013f0b.png)

[CicaTest_iss16-17_02.zip](https://github.com/miiton/Cica/files/1381104/CicaTest_iss16-17_02.zip)

**Comment by hnakamur** [comment]
ありがとうございます！素晴らしいです！
CicaTest_iss16-17_02.zip でOSX Yosemite 10.10.5, Terminal.app, CicaTest 15ptでgjyの下が切れないのを確認しました。

**Comment by miiton** [comment]
ありがとうございます！

**Comment by miiton** [comment]
cmder OK

![win10 before-intellij running 2017-10-13 13-19-33](https://user-images.githubusercontent.com/468745/31530152-2f2cd602-b019-11e7-93f6-4e5454e283bc.png)

**Comment by miiton** [comment]
Cygwin(=mintty？) OK!

![win10 before-intellij running 2017-10-13 13-29-19](https://user-images.githubusercontent.com/468745/31530311-951035d0-b01a-11e7-8bb6-5f9bbfc94ab5.png)

**Comment by hnakamur** [comment]
[msys2](http://www.msys2.org/) の msys2-x86_64-20161025.exe で入れたmintty上で CicaTest_iss16-17_02.zip を使うとjgyの下が切れないことを私の方でも確認しました！ありがとうございます！

**Comment by miiton** [comment]
了解です！クローズします！

**Comment by miiton** [comment]
リリースもしました
https://github.com/miiton/Cica/releases/tag/v2.0.3
