### ISSUE TITLE
Powerlineのグリフに隙間が開く

### ISSUE THREAD

**Issue by miiton** [miiton/Cica#17]
メラメラ燃えるやつ（`0xE0C0`付近、全角幅）にしてたせいで気づかなかったという。。

`0xE0B0` - `0xE0B7`

![cica - vim 2017-10-13 05-53-59](https://user-images.githubusercontent.com/468745/31518678-02662e04-afdb-11e7-8b4e-f4d71839bf5b.png)

**Comment by miiton** [comment]
`set ambiwidth=double` だと上記のように隙間が開きます
`set ambiwidth=single` だと隙間が埋まりますが、その他のアイコン類が見切れます

**Comment by miiton** [comment]
修正完了

**Comment by miiton** [comment]
Windowsだと `set ambiwidth=auto` でいい感じですね

**Comment by raa0121** [comment]
2.0.4 を使ってますが、 `set ambiwidth=double` でこの現象が再発しています。

環境
- Mintty 2.7.9 (msys2付属)
- Vim 8.0.133 (自前ビルド/CentOS)

お手数ですが、確認していただけないでしょうか。

**Comment by miiton** [comment]
ご報告ありがとうございます！確認します！

**Comment by miiton** [comment]
@raa0121 こんな表示になるであっていますか？

![win10 before-mintty running 2017-10-18 09-58-31](https://user-images.githubusercontent.com/468745/31696250-ef3dd44e-b3ea-11e7-93c9-066a11bb50ac.png)

Private Use Areaのグリフ( https://miiton.github.io/Cica/ )が全て強制的に半角サイズにされてしまっているようで、ぺったんこになっていますね。フォント側でどうにか出来なさそうな気がします。 `ambiwidth=single` にすると一応Powerlineのグリフは揃うのは揃いますね

**↓ `ambiwidth=single`**

![win10 before-mintty running 2017-10-18 10-01-58](https://user-images.githubusercontent.com/468745/31696327-669e7c8c-b3eb-11e7-821b-4bddc0be6aa8.png)

**Comment by miiton** [comment]
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf

このフォントで試してみました

**`ambiwidth=double`**

![win10 before-mintty running 2017-10-18 10-16-25](https://user-images.githubusercontent.com/468745/31696616-85cc68f6-b3ed-11e7-9e52-d45431314764.png)

**`ambiwidth=sinble`**

![win10 before-mintty running 2017-10-18 10-17-47](https://user-images.githubusercontent.com/468745/31696638-a25cc8ee-b3ed-11e7-8841-86df90a39faf.png)

Private Use Areaを半角幅で作るとPowerlineのグリフはいい感じになりますが、その他のアイコンが小さくなりすぎてしまうようで、どうしたものかという感じです。

関連 : mintty/mintty#638

**Comment by raa0121** [comment]
検証ありがとうございます。 [mintty が新しいバージョンになった](https://github.com/mintty/mintty/issues/638#issuecomment-338574647)みたいなので、
msys2 に降りてきたら、こちらでも確認してみたいと思います。

**Comment by miiton** [comment]
降りてきてるっぽいですかね？

https://github.com/Alexpux/MSYS2-packages/tree/master/mintty

また確認してみまーす

**Comment by raa0121** [comment]
mintty が 2.8.4 になりましたが、変わらず double 幅だとグリフが欠けますね…

**Comment by miiton** [comment]
🤔

**Comment by miiton** [comment]
`ambiwidth=single` 用と `ambiwidth=double` 用でそれぞれPowerlineグリフを用意するという案を思いついたのでちょっとやってみます

**Comment by miiton** [comment]
確認してみたのですが、バージョンアップ前のようにグリフが強制的にぺちゃんこになる事象は解消しているようです。
ただ、`set ambiwidth=double` 時にPowerlineグリフの右側に黒い背景が出てしまうのは
グリフを半角にしようが関係なく出てしまいます。これはフォントではどうしようもなさそうです...

添付画像はWindows 10 + Cica 2.1.0 + mintty 2.7.9 + Vim 8.0.606 です

![win10 running 2018-02-18 19-54-31](https://user-images.githubusercontent.com/468745/36350990-96dde60c-14e5-11e8-9eb3-3d0bfae25fa3.png)

**Comment by raa0121** [comment]
Cica 3.0.0-rc1 では、良さそうです
![image](https://user-images.githubusercontent.com/237271/41701761-9334c2d0-7568-11e8-8d7b-5c1591a16235.png)

**Comment by miiton** [comment]
おお、確認ありがとうございます
私も改めて確認してみて大丈夫そうならクローズします

**Comment by miiton** [comment]
クローズしますー
