### ISSUE TITLE
罫線がずれる

### ISSUE THREAD

**Issue by hnakamur** [miiton/Cica#18]
[msys2](http://www.msys2.org/) の msys2-x86_64-20161025.exe で入れたmintty上で CicaTest_iss16-17_02.zip を使ってtmuxでウィンドウ分割を行うと
┤
と
├
が左右に少しずれています。

![tmux-keisen-zure1](https://user-images.githubusercontent.com/19299/31541181-cb1477f8-b048-11e7-8c0c-1f031da27c57.png)

![tmux-keisen-zure2](https://user-images.githubusercontent.com/19299/31541194-d5c9e5b6-b048-11e7-8c62-ce74d358de9f.png)

┴
┼
┬
は大丈夫です。

**Comment by miiton** [comment]
ありがとうございます。把握しました。

罫線関連のグリフを全てセンタリングしてしまっている為に発生しているようです。

┤は左寄せになっているべきで、├は右寄せになっているべきですね。

**Comment by miiton** [comment]
MacのAlacritty上のtmuxでもずれてました

**Comment by hnakamur** [comment]
なるほど！となると
┐ 
┘
も左寄せ、
┌
└
も右寄せにする必要があるということですね。
同様に太い罫線も設定変更が必要ですね。

**Comment by miiton** [comment]
調整してみました
罫線関連のグリフ幅が512と1024入り乱れという状態でとても気持ち悪いのですがiTerm2上のtmuxではいけました🤔
今からmintty入れてみますー

![cicatest-regular cicatest-regular ttf unicodefull 2017-10-13 20-42-57](https://user-images.githubusercontent.com/468745/31544731-37f4c66c-b057-11e7-8e68-b5d1d6f2f7c4.png)

[CicaTest_iss18_01.zip](https://github.com/miiton/Cica/files/1382437/CicaTest_iss18_01.zip)

**Comment by miiton** [comment]
あーだめですね😩

**Comment by hnakamur** [comment]
はい、私も試してみましたが、見た目上は変わっていないようです。

**Comment by hnakamur** [comment]
CicaTest_iss18_01.zip を macOS Sierra 10.12.6上でも試してみました。
iTerm2上でtmuxを使うと大丈夫でした。
一方Terminal.appでtmuxだとずれてました。

iTerm2の設定のTextタブの "Treat ambiguous-width characters as double-width" と
Terminal.app の環境設定の詳細タブの 「Unicode 東アジアA (曖昧) の文字幅をW (広) にする」にチェックを付けると ├ ─ ─ ─ のような感じで間が空いて表示されました。

**Comment by miiton** [comment]
これでいけている気がする

[CicaTest_iss18_02.zip](https://github.com/miiton/Cica/files/1382634/CicaTest_iss18_02.zip)

**Comment by miiton** [comment]
横の罫線 `─` が破線になるのが好みが分かれそうですね

**Comment by miiton** [comment]
破線にならない方が綺麗ですね。

フォントを使わない解決法もある（環境によってはまだ？）ようなのでナレッジとして貼っておきます
https://qiita.com/yanma/items/2644e6db6f3bcf249690

**Comment by hnakamur** [comment]
CicaTest_iss18_02.zip でmintty, Terminal.app, iTerm2で罫線のずれが無くなったことを確認しました。
ありがとうございます！

> 横の罫線 ─ が破線になるのが好みが分かれそうですね
そうですねー。曖昧文字の幅について私は良く分かってないです。

ちなみに絵文字はどう表示されるのかと見てみると、曖昧文字のチェックを付けない状態でTerminal.appとiTermで🎉が全角幅で表示されていたのに対し、minttyでは半角幅＋半角スペースで表示されていました。

Cica のレポジトリで `git log .commit_template` で確認しました。

WindowsでVisual Studio CodeのターミナルでWindows Subsystem for Linuxのbashを動かして  `git log .commit_template` だと🎉は全角幅で表示されました。

このイシュー自体はこれでクローズで良さそうですね。

**Comment by hnakamur** [comment]
フォントの罫線を使わない方法もあったんですね。これは知りませんでした。ありがとうございます！
https://github.com/tmux/tmux/releases
を見るとtmux 2.6には取り込まれてそうですね。後ほど試してみます。

**Comment by miiton** [comment]
いい感じにできました！これでリリースします！

![win10 before-mintty running 2017-10-13 22-55-58](https://user-images.githubusercontent.com/468745/31549632-b38b2b10-b069-11e7-9724-db587cb36b76.png)

**Comment by hnakamur** [comment]
修正と2.0.4のリリースありがとうございました！

本題から外れますが、フォントを使わない方法
https://qiita.com/yanma/items/2644e6db6f3bcf249690
についてUbuntu 16.04のtmux 2.6のPPA
https://launchpad.net/~hnakamur/+archive/ubuntu/tmux
を作って `~/.tmux.conf` に以下の設定を追加して試してみたので結果を書いておきます。

```
set -ag terminal-overrides ',*:U8=0'
```

minttyとiTerm2は綺麗に表示されました。
iTerm2は設定で "Treat ambiguous-width characters as double-width" にチェック有り無しどちらでもOKでした。
Terminal.appは環境設定の詳細タブの 「Unicode 東アジアA (曖昧) の文字幅をW (広) にする」をチェック無しにすると綺麗に表示されました。
チェック有りだと分割や切り替えの度に中途半端に表示されたり変な位置に表示されたりしました。
