### ISSUE TITLE
Cica v2 - GOPHER の復活

### ISSUE THREAD

**Issue by tobynet** [miiton/Cica#20]
[DevIcon から NERDFonts へ移行](https://github.com/miiton/Cica/commit/ef07ccef5fef9f80b2e671dd440f0b292cc7e10b#diff-b59a3d53667436f646cb43d366add063L343)された際に、 `上半身Gopher` が削除されている問題があります。

`DevIcon` と  `上半身Gopher`  は、別物と認識しており、移行の際に削除されるものではないと考ます。

![2017-11-15_3nw3p](https://user-images.githubusercontent.com/20859/32806406-bcf70e56-c9cf-11e7-9401-49a6b49ad351.png)

参考:
* `上半身Gopher | U+E160, U+E161` [Home · miiton/Cica Wiki](https://github.com/miiton/Cica/wiki)

**Comment by miiton** [comment]
復活させました！

[Release Cica v2\.0\.5 · miiton/Cica](https://github.com/miiton/Cica/releases/tag/v2.0.5)
