### ISSUE TITLE
曖昧幅の文字列について

### ISSUE THREAD

**Issue by tats-u** [miiton/Cica#21]
丸囲み数字(①～⑳)・罫線(├など)・ギリシャ文字・キリル文字・一部の記号(■など)などは日本語圏と欧米圏では文字幅が異なります。多くの日本語フォントでは全角、多くの非日本語フォントでは半角になっていることが多いですが、このフォントでは統一されていないようです。

罫線・ギリシャ文字・キリル文字はUbuntu Mono由来のようでで半角幅、丸囲み数字・■はRounded Mgen+由来で全角幅になっています。

曖昧幅の文字の文字幅が統一されていないと、端末で統一されていない文字を表示する際に文字幅・文字間隔がおかしくなる問題が生じます。

![image](https://user-images.githubusercontent.com/12870451/34751265-dd762e32-f5ee-11e7-8c65-88eaae0bc7e8.png)

**Comment by miiton** [comment]
はい、そうなっています。

罫線はtmuxの罫線を想定して半角幅にしていますし、丸数字や四角などの記号は日本語と合わせて使うことを想定して全角幅になっています。

統一する予定はありませんが、このグリフは全角幅のほうが美しい、半角幅のほうが美しいなどがあれば、エディタや端末によって曖昧幅の扱いが異なることを考慮した上で調整はしていきます。

**Comment by miiton** [comment]
本件問題とは思っておりませんので、クローズさせて頂きます。

もし、「いやいや、こういう時に明らかにおかしくなる」など事例がありましたら、
エディタやOSなどの情報とあわせてご提示頂けると助かります。
