### ISSUE TITLE
Noto Emoji抜きバージョン

### ISSUE THREAD

**Issue by miiton** [miiton/Cica#29]
参考ご意見 : https://twitter.com/mattn_jp/status/1007079705705500672

WindowsでDirectXが有効な環境で白黒のNoto Emojiが表示されるが、視認性が悪いと感じる。
気に入ってる人もいると思うのでNoto Emoji抜きバージョンを検討

**Comment by raa0121** [comment]
私もmattn さんと同意見です。

**Comment by miiton** [comment]
コメントありがとうございます

フォント名は変えたくないので、フォルダ分けで絵文字抜きバージョンを追加する方向で検討しています
