### ISSUE TITLE
FireCode のようなリガチャ(合字)が欲しい

### ISSUE THREAD

**Issue by raa0121** [miiton/Cica#31]
作るのにどれくらいかかるかわかりませんが、欲しいです。

**Comment by miiton** [comment]
リガチャは対応しない予定です
面白いのは面白いのですが、視認性、判読性が良いか？と言われると疑問なのと、書籍や技術系サイトで見たコードと違いすぎてしまいますので。
対応するなら別プロジェクトかなと思います。

**Comment by raa0121** [comment]
このプロジェクトでは扱わない旨、了解です
