### ISSUE TITLE
tmux, vim-airline でセパレータが表示されない

### ISSUE THREAD

**Issue by sui74** [miiton/Cica#32]
<img width="1680" alt="cicafont01" src="https://user-images.githubusercontent.com/32660645/42787352-0cc77044-8995-11e8-8760-f54a17bea13a.png">Cica v3

<img width="1680" alt="mononokinf01" src="https://user-images.githubusercontent.com/32660645/42787831-49de4adc-8997-11e8-8204-65e735a21e25.png">参考）mononoki nerd font

Ubuntu 18.04 LTS
tmux 2.6 (powerline)
vim 8.0 (vim-airline)

左向きの三角形のセパレータのみ表示されません
ステータスラインを確認したところ、手前の記号（#）にセパレータの三角形が重なっています
Cicaフォントはv3のビルド済みのものを使用中です

**Comment by miiton** [comment]
@sui74 

おそらくambiwidthの設定云々が関係していると思います
関連 #4 #10 #17 

Ubuntuデスクトップのターミナルの設定やvimの設定でambiwidthの設定が変更可能であれば一度切り替えて確認してみてもらえますか？

場合によってはambiwidth=single用とdouble用の2種類バンドルする作戦も考えます...

**Comment by miiton** [comment]
Ubuntuデスクトップを普段使いしていないのでなんともわからないのですが、全角設定を有効にした状態で普段使いできるものなのか、そうではなくフォントが半角幅に対応していたほうがより良いのか、どちらでしょうか？

vscodeはChromiumベースなので表示できていると想像します

**Comment by sui74** [comment]
SSに文章を添えるのが抜けてました...すみません！

全角を有効にした状態だとpowerlineの表示が崩れてしまい使用に差し支えるので、半角幅へ対応していただけると嬉しいです（他のpowerline対応フォントと表示が揃うので綺麗だと思います）
こちらは私の要望になりますので本件はクローズしていただいて大丈夫です、ありがとうございました...！

**Comment by sui74** [comment]
SSに文章を添えるのが抜けてました...すみません！

全角を有効にした状態だとpowerlineの表示が崩れてしまい使用に差し支えるので、半角幅へ対応していただけると嬉しいです（他のpowerline対応フォントと表示が揃うので綺麗だと思います）
これは要望になりますので、クローズします。ありがとうございました
