### ISSUE TITLE
リリースページにビルド済みのフォントがない

### ISSUE THREAD

**Issue by narugit** [miiton/Cica#35]
[READMEのダウンロード部分](https://github.com/miiton/Cica#%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89)の説明では、
リリースページにビルド済みのフォントがあると説明されていますが、
リリースページにあるzipファイルを解凍してもビルド済みのフォントが見当たりませんでした。

Cica v3.0.0のzipファイル解凍結果は以下の通りでした。
```
dist/
  |- noemoji/
    |- .gitkeep
  |- .gitkeep
screenshots/
  |- ss1.png
sourceFonts/
  |- gopher.sfd
  |- nerd.ttf
test/
  |- test_glyphs.py
tmp/
  |- .gitkeep
.commit_template
.gitignore
CHANGELOG.md
cica.py
COPYRIGHT.py
index.html
LICENSE.txt
README.md
wercker.yml
```

ご確認の程、よろしくお願いいたします。

**Comment by narugit** [comment]
#34 を読んで理解致しました、close致します。
お騒がせして申し訳ございません。

**Comment by miiton** [comment]
ライセンスを見直したバージョンをリリースしました

https://github.com/miiton/Cica/releases/tag/v4.0.0

**Comment by narugit** [comment]
ご連絡頂き、ありがとうございます！
