### ISSUE TITLE
Vueのアイコンが欲しい

### ISSUE THREAD

**Issue by miiton** [miiton/Cica#37]
Twitter上でご意見を見かけたので

NerdFontsが組み込んでいる [Devicons](https://github.com/vorillaz/devicons) がメンテナンスされていないので、 [Icons for Devs](https://github.com/mirmat/iconsfordevs) に置き換えられるか検討する。ライセンスは MIT なので問題ないはず。

- [x] UnicodeアドレスはDevIconsと同じか？ -> 違うので追加するだけでOK
- [x] vim-deviconsで追加したアイコン表示できるか？ -> とりあえずプルリクなしでいける [Add support for \.vue files\. · Issue \#235 · ryanoasis/vim\-devicons](https://github.com/ryanoasis/vim-devicons/issues/235)
- [x] ライセンスは問題ないか？ -> MITライセンス

## 参考

- https://twitter.com/naron__A/status/1041279932905578496

**Comment by miiton** [comment]
グリフさえ足したらいけるっぽい

参考: https://github.com/ryanoasis/vim-devicons/issues/235

**Comment by miiton** [comment]
Unicode違う模様🤔

**Comment by miiton** [comment]
`U+E900` 〜 `U+E950` を追加してみる。（Vueは `U+E905`）

**Comment by miiton** [comment]
👍

![hoge-vue - vim 2018-09-17 09-05-44](https://user-images.githubusercontent.com/468745/45602419-e8c65300-ba58-11e8-9557-03b469e5fe93.png)

**Comment by miiton** [comment]
#39 で表示ずれ対応しますので、一旦こちらはクローズします。

**Comment by karchz** [comment]
4.1.1でもVueアイコンは含まれていないようですが、u+e905で間違いないのでしょうか？
