### ISSUE TITLE
LinuxのGNOME 端末(GNOME-Terminal)でCica4.1.1をフォントに設定できない。

### ISSUE THREAD

**Issue by Row-8671** [miiton/Cica#40]
Linux(Ubuntu)のGNOME端末(GNOME-Terminal)でCicaフォントを4.1.1から設定できなくなりました。
なにか前バージョンと仕様の違いがあるのでしょうか？

**Comment by Row-8671** [comment]
@miiton 
URLにあった方法で設定したらできました。
ありがとうございました！！

**Comment by miiton** [comment]
@Row-8671 よかったです！

@naronA 記事参照させていただきました、ありがとうございます！
