### ISSUE TITLE
新元号対応

### ISSUE THREAD

**Issue by miiton** [miiton/Cica#42]
令 `U+4EE4` と 和 `U+548C` をぎゅっと絞って`U+32FF`に

参考: [The Unicode Blog: New Japanese Era](http://blog.unicode.org/2018/09/new-japanese-era.html)

**Comment by tsuyoshicho** [comment]
reopenが必要かは不明ですが

https://github.com/adobe-fonts/source-han-sans/releases/tag/2.001

[Adobe、新元号“令和”の合字を追加した「源ノ角ゴシック」v2\.001をリリース \- 窓の杜](https://forest.watch.impress.co.jp/docs/news/1179218.html)

で正式対応したようです。

最新版での生成処理したら、源ゴ経由で埋め込まれますかね?
