### ISSUE TITLE
Vista.vimで使われているアイコンを表示できない

### ISSUE THREAD

**Issue by t-shin-komae** [miiton/Cica#45]
Vista.vimというプラグインで使われる文字が一部、表示されない、またはNerdTree fontと異なるものが表示されます。

例:
uf794:
uf71b:

ubuntu18.04のgnome-terminal(フォントはCicaに変更済み)上でneovimを動かしています。

**Comment by miiton** [comment]
@t-shin-komae 
ご報告ありがとうございます、CicaがNerd Fontsの更新についていっていない為ですね、
該当のグリフは Material Design Icons に含まれているようです。ちょっと試してみます。

**Comment by miiton** [comment]
（メモ）

https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/renderer.vim#L5-L42

`U+E22B` などがCica v4のグリフとかぶるのでv5としてのリリースになる見込み

**Comment by miiton** [comment]
（メモ）

![No Name  + - VIM 2019-06-04 23-04-00](https://user-images.githubusercontent.com/468745/58885504-4e5c8b80-871d-11e9-9d86-d4997a73a498.png)

![No Name  + - VIM 2019-06-04 23-07-41](https://user-images.githubusercontent.com/468745/58885906-fb370880-871d-11e9-9d7c-656fa14a8bb8.png)

**Comment by miiton** [comment]
Nerd Fontsがこういう実装になっているのですが、`0xfb00` 〜 はアラビア文字に被ってしまっており、Vimできちんと表示されない（ambiwidthではない為）のでこの部分は取り込まないようにするかもしれません

**Comment by miiton** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/346

こちらのIssueにある通り、`U+F0000` 〜 `U+FFFFD` に追加するの良さそうかな？

**Comment by miiton** [comment]
![korejanai](https://user-images.githubusercontent.com/468745/58954136-40694200-87d3-11e9-8274-e7fe3cfa2a19.gif)

🤔

**Comment by miiton** [comment]
ここまで持っていけました。

![Cica) - VIM 2019-06-06 00-04-21](https://user-images.githubusercontent.com/468745/58967285-e5454880-87ee-11e9-9c6e-5a48746d7e5b.png)

`ambiwidth=double` の環境限定です。`single` になるとアイコンが半分欠けてしまうので(´・ω・`)

**Comment by miiton** [comment]
おまたせしました v5.0.1 でいい感じに表示できると思います

以下設定例です。

```vim
" Vista

let g:vista_icon_indent = ["󳄀󳄂 ", "󳄁󳄂 "]
let g:vista_default_executive = 'coc'
let g:vista#renderer#icons = {
            \ 'func':           "\Uff794",
            \ 'function':       "\Uff794",
            \ 'functions':      "\Uff794",
            \ 'var':            "\Uff71b",
            \ 'variable':       "\Uff71b",
            \ 'variables':      "\Uff71b",
            \ 'const':          "\Uff8ff",
            \ 'constant':       "\Uff8ff",
            \ 'method':         "\Uff6a6",
            \ 'package':        "\Ufe612",
            \ 'packages':       "\Ufe612",
            \ 'enum':           "\Uff435",
            \ 'enumerator':     "\Uff435",
            \ 'module':         "\Uff668",
            \ 'modules':        "\Uff668",
            \ 'type':           "\Ufe22b",
            \ 'typedef':        "\Ufe22b",
            \ 'types':          "\Ufe22b",
            \ 'field':          "\Uff93d",
            \ 'fields':         "\Uff93d",
            \ 'macro':          "\Uff8a3",
            \ 'macros':         "\Uff8a3",
            \ 'map':            "\Uffb44",
            \ 'class':          "\Uff9a9",
            \ 'augroup':        "\Uffb44",
            \ 'struct':         "\Uffb44",
            \ 'union':          "\Uffacd",
            \ 'member':         "\Uff02b",
            \ 'target':         "\Uff893",
            \ 'property':       "\Uffab6",
            \ 'interface':      "\Uffa52",
            \ 'namespace':      "\Uff475",
            \ 'subroutine':     "\Uff915",
            \ 'implementation': "\Uff87a",
            \ 'typeParameter':  "\Uff278",
            \ 'default':        "\Uff29c"
            \ }
```

**Comment by miiton** [comment]
↑ `vista_icon_indent` のところはv5.0.1をインストールして頂いた状態でコピペでいける...はず...!!

**Comment by miiton** [comment]
![Cica) - VIM 2019-06-27 09-03-34](https://user-images.githubusercontent.com/468745/60223032-78d3db80-98ba-11e9-84b4-0e2dd416f6a8.png)

こんな感じになります

**Comment by miiton** [comment]
閉じますー
