### ISSUE TITLE
下線がずれて表示される

### ISSUE THREAD

**Issue by cryks** [miiton/Cica#5]
<img width="324" alt="underline" src="https://cloud.githubusercontent.com/assets/420416/17146196/7caf1874-5398-11e6-8532-a90b51d142c7.png">
(PuTTY DirectWrite version)

Underline positionの値がおかしいようです。
-100あたりに手動で修正してやるとうまい具合に表示されました。

**Comment by miiton** [comment]
@cryks レスポンス遅れました・・・ご報告ありがとうございます

すごいずれていますね・・・
手元の環境で確認してみたんですが、PuttyのDirectWrite版で確認したところ、確かに少しずれている用に見えるのですが、 @cryks さんの環境程ずれておらず、何かPuttyの設定が必要でしょうか？

![lab-win10](https://cloud.githubusercontent.com/assets/468745/17465287/1baceb56-5d2e-11e6-8670-f8de13b771cd.png)

**Comment by miiton** [comment]
ちなみに
http://ice.hotmint.com/putty/d2ddw.html
の `putty-d2ddw-20160306.zip` で確認しました

**Comment by cryks** [comment]
PuTTY DW版のデフォルト設定からフォントだけを変更して試してみましたが、やはり壮大にずれます。
フォントサイズかなと思って、サイズをいろいろ変更してみても同じでした。
PuTTY公式(や、PuTTY DW版のサイトで公開されているGDI版)ではずれませんでした。
DirectWriteのバージョン違いとかですかね…？(当方Windows10です)

**Comment by miiton** [comment]
了解です。先ほどMacのiTerm上でも同様のずれを確認出来ました。
ありがとうございます。

FontForgeの関数になぜか `Underline position` を変更するものが見当たらないので、
とりあえずこの問題だけPythonで実装する方針に・・・

![1__tmux](https://cloud.githubusercontent.com/assets/468745/17646162/160c827c-61f9-11e6-8b6a-01519dd3ffca.png)

**Comment by miiton** [comment]
修正してリリースしました。ありがとうございました！ ＞ @cryks

[Release Cica v1.0.2 · miiton/Cica](https://github.com/miiton/Cica/releases/tag/v1.0.2)

![1__nvim](https://cloud.githubusercontent.com/assets/468745/17656465/619cddd4-62f5-11e6-8c6b-2d122f0db526.png)
