### ISSUE TITLE
urxvtでVista.vimのためのアイコンが表示できない

### ISSUE THREAD

**Issue by mopp** [miiton/Cica#56]
使用バージョンなど
- OS: Arch linux 5.3.13-arch1-1
- Cica: 5.0.1
- Terminal
  - rxvt-unicode 9.22-9
  - sakura 3.7.0-1

#45 を参考にVista.vimの設定をしましたが、urxvtで表示することができませんでした
ターミナルの問題か、フォントの問題かを切り分けるために別のSakuraというターミナルを使用したところ正常に表示できました
![2019-12-01-124540_1889x1303_scrot](https://user-images.githubusercontent.com/1330045/69909106-094db380-1439-11ea-9233-a79e8e72e81c.png)
左がurxvt、右がSakuraです

しかし、`nerd-fonts-inconsolata 2.0.0-2`をインストールして、urxvtのフォント設定を次のようにし、Vista.vimの設定は一切無しでVimを起動すると、Vista.vim標準の絵文字を表示することができました。

```xdefaults
URxvt.font: xft:Cica:style=Regular:size=12, xft:Inconsolata Nerd Font Mono 
```

![2019-12-01-125445_1079x1323_scrot](https://user-images.githubusercontent.com/1330045/69909137-c50ee300-1439-11ea-9245-49ee3baf3eba.png)

また、Cicaの絵文字(💪など)はurxvt上できちんと表示されます。
ですので、Cicaの該当部分の絵文字が他となにか異なるのではないか？と考えてIssueを立てました

(フォントにはあまり詳しくないのですが、urxvt自体の問題であればこちらにIssueを立てるのは変なのでCloseしてくれて構わないです)

**Comment by miiton** [comment]
@mopp 
遅レスすいません😩

なんとなくですが、事象を見た感じurxvtがサロゲートペアに対応していないのではないかなと思いました。

[Unicode \- Wikipedia](https://ja.wikipedia.org/wiki/Unicode#%E6%8B%A1%E5%BC%B5%E9%A0%98%E5%9F%9F)

**Comment by mopp** [comment]
@miiton 
urxvtとサロゲートペアで調べてみましたがわかりませんでした…
なんにせよ、urxvtの都合のようなのでcloseします
ありがとうございます 🙏
