### ISSUE TITLE
gvim で特定のグリフが豆腐になる

### ISSUE THREAD

**Issue by raa0121** [miiton/Cica#81]
gvim で Vue のアイコンである、`0xffd42` やその周辺のグリフが豆腐になります。
gvim 上で、以下のコマンドで再現できます。
```
:echo "\ufd42"
```
検証環境
- Windows gvim 9.0.1153 / 9.0.1167
- Linux gvim 9.0.1046 / 9.0.1171

https://user-images.githubusercontent.com/237271/211610873-edb74658-f1f8-4a41-921b-b76e6f989496.mp4

@kuuote さん提供Linux のスクショ
![image](https://user-images.githubusercontent.com/237271/211611843-bf00c4d8-d19a-4150-9afd-60e111b2a5cc.png)

**Comment by miiton** [comment]
画像貼っていただいている `U+FD42` にはグリフの登録無いですね

![image](https://user-images.githubusercontent.com/468745/211678730-9d5ff249-8a61-4944-807a-0e8476490a2f.png)

Vueのアイコンは `U+FFD42` です

![image](https://user-images.githubusercontent.com/468745/211678782-a8fb01e4-e75c-4dfa-9c70-1d6f65b2087c.png)

Vimだと `u` → `U` で

```
:echo "\Uffd42"
```

で出ます 👍

**Comment by raa0121** [comment]
回答ありがとうございます。
https://raw.githubusercontent.com/lambdalisue/nerdfont.vim/master/assets/json/extension.json をブラウザで開いても、Vue だけ豆腐になりますね…。
https://github.com/miiton/Cica/issues/45#issuecomment-498690013 から、Material Design Icons を取り込んでる位置が、他 nerdfont patch を当てているフォントのグリフと、Cica のグリフの位置が違うようですね…。
![image](https://user-images.githubusercontent.com/237271/211696718-c9e0fd48-1692-42b1-8595-2596f9cfd11c.png)

**Comment by miiton** [comment]
ですねー！その画像の、例えば vim は `U+E62B` で Private Use Area に配置されているグリフなんですが、 vue は `U+FD42` でアラビア文字領域を侵食していて「なんで？」という感じですね。

現状のCicaはフォント開発視点でのお作法としては⭕、互換性としては❌という認識です。

👇のIssueの動向次第で互換性⭕にもっていけたら良いかなと！
[\[Suggestion\] Fix invalid code points for some glyphs · Issue \#365 · ryanoasis/nerd\-fonts](https://github.com/ryanoasis/nerd-fonts/issues/365)

**Comment by raa0121** [comment]
ありがとうございます。
今のところ、そこまで困るものでもないので、Cica 側で対応頂く必要はありません。
気が向いたら、 nerdfont.vim の Cica 対応パッチを書こうと思います。
